### ISSUE TITLE
EU driving license

### ISSUE THREAD

**Issue by androidsx2** [mindee/mindee-api-java#142]
Hi!

i try to scan Greek (EU) driving licenses but the results are not as expected,
eg Country Code, First/Last Name, ..

plz, advise
![image](https://github.com/mindee/mindee-api-java/assets/54938356/331f5861-3cf1-4e29-ae12-6b34a5561034)

**Comment by ianardee** [comment]
You can try to use the International ID product which has full support of non-latin writing systems.

https://github.com/mindee/mindee-api-java/blob/main/docs/code_samples/international_id_v2_async.txt
