### ISSUE TITLE
Add sample codes

### ISSUE THREAD

**Issue by Kvindee** [mindee/mindee-api-java#83]
Main goal is to provide code samples for all supported APIs and ensure these samples work properly.

Sample code files are to be placed in the `docs/code_samples` directory.

Each sample is a **.txt** file.

The contents of each file should be Java code that can be run from command line with only a few changes:

* replace `my-api-key` with the actual API key from github secrets
* replace `/path/to/the/file.ext` with the actual file path

Files to create:

* all supported OTS APIs => `<api_url>_<api_version>.txt`, i.e. `expense_receipts_v4.txt` for Receipts v4
* custom API => `custom_1.txt`
* default (not in the Java SDK) => `default.txt`

There should be a shell script that runs over all files in the folder and calls the API with a blank file.
Use the following as an example: https://github.com/mindee/mindee-api-dotnet/blob/main/test_sample_code.sh

No need  to check the return of the server, however the script should fail on API errors (normally `set -e` should take care of that).

There should be a GitHub action that:

* installs the project locally with Maven
* executes the shell script defined above

This action should be run on any push to `main` and once a day.

Use the following as an example: https://github.com/mindee/mindee-api-dotnet/blob/main/.github/workflows/test-sample-codes.yml

**Comment by ianardee** [comment]
@vivekpaddy I'll let you know when we have the API key available in Github. For now you can test locally ;-)
